FROM registry.access.redhat.com/ubi8:8.0

RUN curl -o /usr/local/bin/roxctl https://mirror.openshift.com/pub/rhacs/assets/3.70.0/bin/Linux/roxctl
RUN chmod +x /usr/local/bin/roxctl

CMD tail -f /dev/null
