apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: roxctl-cli
    app.kubernetes.io/component: roxctl-cli
    app.kubernetes.io/instance: roxctl-cli
  name: roxctl-cli
  namespace: day2ops
spec:
  replicas: 1
  selector:
    matchLabels:
      deployment: roxctl-cli
  template:
    metadata:
      labels:
        deployment: roxctl-cli
    spec:
      volumes:
      - name: backup-volume
        persistentVolumeClaim:
          claimName: rhacs-bkp-afs
      - name: config-volume
        configMap:
          name: rhacs-config
      containers:
      - image: registry.redhat.io/advanced-cluster-security/rhacs-roxctl-rhel8:3.70.0
        imagePullPolicy: IfNotPresent
        name: roxctl-cli
        volumeMounts:
        - name: config-volume
          mountPath: /rhacs-config
        - name: backup-volume
          mountPath: /backup
        command:
        - /bin/bash
        - -c
        - |
          #!/usr/bin/env bash
          echo "To restore RHACS central database, run \"ls -l /backup\" to list available online backups, then run below command:"
          echo "roxctl --ca /rhacs-config/rhacs_ca_crt --token-file /rhacs-config/rhacs_api_token -e \$(cat /rhacs-config/rhacs_endpoint) central db restore /backup/<backup-file-name>"
          while true; do sleep 30; done;  
      restartPolicy: Always
